-- Insert 100 famous Scottish castles
INSERT INTO castles (id, name, region, type, built_century, latitude, longitude, description, visiting_info, best_seasons, admission_fee, managed_by, rank) VALUES
('1', 'Edinburgh Castle', 'Edinburgh', 'Royal Castle', '12th Century', 55.9486, -3.1999, 'Scotland''s most famous castle, perched on Castle Rock overlooking the capital. Home to the Crown Jewels, Stone of Destiny, and the One O''Clock Gun.', 'Open daily with timed entry tickets. Allow 2-3 hours for full visit.', '{"April", "May", "June", "July", "August", "September"}', 'Adult £19.50', 'Historic Environment Scotland', 1),
('2', 'Stirling Castle', 'Stirling', 'Royal Castle', '12th Century', 56.1242, -3.9456, 'One of Scotland''s grandest castles with spectacular views. Witness to many pivotal moments in Scottish history including battles and royal ceremonies.', 'Open daily. Great for families with interactive exhibits and costumed interpreters.', '{"April", "May", "June", "July", "August", "September"}', 'Adult £16.00', 'Historic Environment Scotland', 2),
('3', 'Eilean Donan Castle', 'Highland', 'Clan Castle', '13th Century', 57.2742, -5.5164, 'Scotland''s most photographed castle, situated on a small tidal island. Featured in countless films and offering breathtaking Highland scenery.', 'Open March to October. Popular for weddings and photography. Book ahead in summer.', '{"May", "June", "July", "August", "September"}', 'Adult £10.00', 'Private', 3),
('4', 'Urquhart Castle', 'Highland', 'Historic Fortress', '13th Century', 57.3230, -4.4364, 'Dramatic ruins overlooking Loch Ness. Perfect for monster spotting! One of Scotland''s largest castles with a fascinating visitor centre.', 'Open daily with excellent visitor centre. Great views over Loch Ness.', '{"April", "May", "June", "July", "August", "September"}', 'Adult £11.00', 'Historic Environment Scotland', 4),
('5', 'Caerlaverock Castle', 'Dumfries and Galloway', 'Historic Fortress', '13th Century', 55.0057, -3.5262, 'Unique triangular castle with impressive twin-towered gatehouse. Surrounded by a water-filled moat and set in beautiful countryside.', 'Open daily. Family-friendly with nature reserve nearby. Medieval siege machine demonstrations.', '{"April", "May", "June", "July", "August", "September"}', 'Adult £6.00', 'Historic Environment Scotland', 5),
('6', 'Dunnottar Castle', 'Aberdeenshire', 'Historic Fortress', '14th Century', 56.9461, -2.1969, 'Dramatic clifftop ruins where the Scottish Crown Jewels were once hidden. Spectacular coastal location with breathtaking views.', 'Open daily. Steep walk down to castle. Stunning photography opportunities.', '{"April", "May", "June", "July", "August", "September"}', 'Adult £7.00', 'Private', 6),
('7', 'Glamis Castle', 'Angus', 'Royal Castle', '14th Century', 56.6206, -3.0186, 'Childhood home of the Queen Mother and birthplace of Princess Margaret. Beautiful fairy-tale castle with magnificent gardens.', 'Guided tours of castle and grounds. Famous for its ghosts and royal connections.', '{"April", "May", "June", "July", "August", "September", "October"}', 'Adult £15.50', 'Private', 7),
('8', 'Culzean Castle', 'South Ayrshire', 'Palace', '18th Century', 55.3494, -4.7894, 'Elegant castle designed by Robert Adam, perched on dramatic cliffs. Beautiful country park with beaches and woodland walks.', 'Castle and country park. Perfect for families. Eisenhower exhibition.', '{"April", "May", "June", "July", "August", "September", "October"}', 'Adult £18.50', 'National Trust for Scotland', 8),
('9', 'Inveraray Castle', 'Argyll and Bute', 'Clan Castle', '18th Century', 56.2332, -5.0743, 'Fairy-tale castle and ancestral home of the Duke of Argyll. Beautiful lakeside location with stunning interiors and armory.', 'Open April to October. Famous for Downton Abbey filming. Beautiful gardens.', '{"April", "May", "June", "July", "August", "September", "October"}', 'Adult £13.00', 'Private', 9),
('10', 'Balmoral Castle', 'Aberdeenshire', 'Royal Castle', '19th Century', 57.0435, -3.2269, 'The Royal Family''s private residence in Scotland. Beautiful estate with gardens, exhibitions and stunning Highland scenery.', 'Open April to July only. Ballroom and grounds. Book exhibitions in advance.', '{"April", "May", "June", "July"}', 'Adult £15.00', 'Royal Family', 10),
('11', 'Craigievar Castle', 'Aberdeenshire', 'Historic Fortress', '17th Century', 57.2089, -2.6789, 'Pink fairy-tale castle that inspired Disney. Remarkable seven-story tower house with original painted ceilings.', 'Limited access - exterior viewing and some interior tours. Very popular.', '{"May", "June", "July", "August", "September"}', 'Adult £12.00', 'National Trust for Scotland', 11),
('12', 'Cawdor Castle', 'Highland', 'Clan Castle', '14th Century', 57.5055, -3.9989, 'Beautiful castle associated with Shakespeare''s Macbeth. Stunning gardens and fascinating family history.', 'Open May to October. Private family home with beautiful gardens.', '{"May", "June", "July", "August", "September", "October"}', 'Adult £12.00', 'Private', 12),
('13', 'Castle Fraser', 'Aberdeenshire', 'Historic Fortress', '16th Century', 57.2856, -2.5198, 'Spectacular Z-plan castle, one of the most elaborate tower houses in Scotland. Beautiful parkland and walled garden.', 'Open Easter to October. Family-friendly with adventure playground.', '{"April", "May", "June", "July", "August", "September", "October"}', 'Adult £12.50', 'National Trust for Scotland', 13),
('14', 'Floors Castle', 'Scottish Borders', 'Palace', '18th Century', 55.6067, -2.4567, 'Scotland''s largest inhabited castle, home to the Duke of Roxburghe. Magnificent art collection and beautiful gardens.', 'Open Easter to October. Family home with excellent tearoom.', '{"April", "May", "June", "July", "August", "September", "October"}', 'Adult £12.00', 'Private', 14),
('15', 'Tantallon Castle', 'East Lothian', 'Historic Fortress', '14th Century', 56.0572, -2.6478, 'Spectacular clifftop fortress facing the Bass Rock. Massive red sandstone walls and dramatic coastal setting.', 'Open daily. Excellent for photography and birdwatching. Windy location!', '{"April", "May", "June", "July", "August", "September"}', 'Adult £6.00', 'Historic Environment Scotland', 15),
('16', 'Doune Castle', 'Stirling', 'Historic Fortress', '14th Century', 56.1859, -4.0506, 'Well-preserved medieval castle famous for Monty Python and Outlander filming. Excellent audio guide narrated by Terry Jones.', 'Open daily. Famous film location. Interactive audio guide included.', '{"April", "May", "June", "July", "August", "September"}', 'Adult £6.00', 'Historic Environment Scotland', 16),
('17', 'Kilchurn Castle', 'Argyll and Bute', 'Clan Castle', '15th Century', 56.4089, -5.0267, 'Romantic ruins on Loch Awe with stunning mountain backdrop. One of Scotland''s most photographed castle ruins.', 'Seasonal access. Free entry. Beautiful for photography. Can be reached by boat.', '{"April", "May", "June", "July", "August", "September", "October"}', 'Free', 'Historic Environment Scotland', 17),
('18', 'Blackness Castle', 'West Lothian', 'Historic Fortress', '15th Century', 55.9825, -3.5156, 'Ship-shaped fortress on the Forth, nicknamed "the ship that never sailed". Featured in Outlander as Fort William.', 'Open daily. Unusual ship-like design. Great views over the Forth.', '{"April", "May", "June", "July", "August", "September"}', 'Adult £6.00', 'Historic Environment Scotland', 18),
('19', 'Crathes Castle', 'Aberdeenshire', 'Historic Fortress', '16th Century', 57.0978, -2.5267, 'Beautiful tower house with remarkable painted ceilings and stunning gardens. Famous for its topiary and herbaceous borders.', 'Open daily. Magnificent gardens. Family-friendly with adventure playground.', '{"April", "May", "June", "July", "August", "September", "October"}', 'Adult £13.50', 'National Trust for Scotland', 19),
('20', 'Duart Castle', 'Isle of Mull', 'Clan Castle', '13th Century', 56.4556, -5.6578, 'Ancestral seat of Clan MacLean on dramatic clifftop overlooking the Sound of Mull. Recently restored with clan exhibitions.', 'Open May to October. Spectacular location. Rich clan history.', '{"May", "June", "July", "August", "September", "October"}', 'Adult £7.50', 'Private', 20);

-- Success message for castles
SELECT 'First 20 castles inserted successfully!' as status;
