-- Insert 30 Scottish Hidden Gems (Safe Version - Won't conflict with existing data)
INSERT INTO hidden_gems (id, name, region, type, latitude, longitude, description, how_to_find, best_seasons, difficulty_level, requires_hiking, nearest_town, special_features, photography_tips, rank) VALUES
('1', 'Fairy Pools', 'Isle of Skye', 'Hidden Waterfall', 57.2444, -6.2669, 'Crystal clear blue pools and waterfalls cascading down from the Black Cuillin mountains. A magical series of natural swimming holes.', 'Park at Glen Brittle and follow the well-marked path for 1.2 miles along the river. The trail is mostly flat with some rocky sections.', '{"April", "May", "June", "July", "August", "September"}', 'Easy', true, 'Glen Brittle', 'Crystal clear blue water, natural swimming pools, dramatic mountain backdrop', 'Best light is early morning or late afternoon. Use polarizing filter to cut water reflections.', 1),
('2', 'The Quiraing', 'Isle of Skye', 'Natural Wonder', 57.6444, -6.3669, 'Otherworldly rock formations created by ancient landslides. A mystical landscape of towering rock pinnacles and hidden valleys.', 'Drive to Staffin and take the single-track road towards Uig. Park at the designated area and hike up the winding path.', '{"May", "June", "July", "August", "September"}', 'Moderate', true, 'Staffin', 'Dramatic rock formations, hidden valleys, 360-degree views', 'Golden hour creates stunning shadows. Wide-angle lens captures the scale. Watch for changing weather.', 2),
('3', 'Fingal''s Cave', 'Isle of Mull', 'Cave System', 56.4322, -6.3369, 'Natural cathedral formed by hexagonal basalt columns. The cave inspired Mendelssohn''s Hebrides Overture with its incredible acoustics.', 'Take boat tour from Oban or Iona. The cave is only accessible by sea. Tours run April to October weather permitting.', '{"April", "May", "June", "July", "August", "September"}', 'Easy', false, 'Oban', 'Hexagonal basalt columns, incredible natural acoustics, puffin colonies nearby', 'Capture the geometric patterns of basalt. Use flash to illuminate cave interior. Telephoto for puffins.', 3),
('4', 'Sandwood Bay', 'Highland', 'Secret Beach', 58.5567, -5.1089, 'One of Scotland''s most remote and beautiful beaches. A pristine stretch of pink sand backed by dunes and sea cliffs.', 'Park at Blairmore and hike 4 miles across moorland. The path is clear but can be boggy. Allow 3-4 hours round trip.', '{"May", "June", "July", "August", "September"}', 'Moderate', true, 'Kinlochbervie', 'Pink sand beach, 100ft sea stack, completely undeveloped', 'Sunset shots are spectacular. Include the Am Buachaille sea stack. Bring weather protection.', 4),
('5', 'Caerlaverock Nature Reserve', 'Dumfries and Galloway', 'Natural Wonder', 55.0456, -3.5267, 'Massive mudflats and saltmarsh hosting thousands of migratory birds including barnacle geese and whooper swans.', 'Follow signs from Caerlaverock village. The visitor centre has hides and guided walks. Best viewing from October to March.', '{"October", "November", "December", "January", "February", "March"}', 'Easy', false, 'Caerlaverock', 'Barnacle geese spectacle, bird hides, medieval castle nearby', 'Long telephoto lens essential. Early morning for best bird activity. Camouflage clothing helps.', 5),
('6', 'Glen Coe''s Hidden Valley', 'Highland', 'Mountain Peak', 56.6789, -5.1056, 'Secret valley where Clan MacDonald once hid stolen cattle. A dramatic mountain sanctuary accessed through a narrow gorge.', 'Park at Three Sisters car park in Glen Coe. Follow tourist path then branch right up the steep scree slope to the hidden entrance.', '{"April", "May", "June", "July", "August", "September"}', 'Challenging', true, 'Glencoe Village', 'Secret valley, dramatic mountain walls, historical clan hiding place', 'Wide shots capture the enclosed feeling. Include people for scale. Weather can change rapidly.', 6),
('7', 'Smoo Cave', 'Highland', 'Cave System', 58.5678, -4.7189, 'Massive sea cave with underground waterfall and chamber system. One of Scotland''s largest and most accessible caves.', 'Located right by the A99 road near Durness. Easy walk from car park. Boat trips explore inner chambers.', '{"All year"}', 'Easy', false, 'Durness', 'Underground waterfall, huge entrance chamber, boat trips to inner caves', 'Use tripod for low light. Flash bouncing off walls creates drama. Include waterfall in compositions.', 7),
('8', 'Loch Coruisk', 'Isle of Skye', 'Remote Island', 57.2089, -6.1456, 'Remote mountain loch surrounded by the jagged peaks of the Black Cuillin. Accessible only by boat or challenging hike.', 'Take boat from Elgol (easier) or hike from Glen Brittle via the Bad Step (expert level). Boat trips run April to October.', '{"April", "May", "June", "July", "August", "September"}', 'Expert', true, 'Elgol', 'Complete isolation, dramatic mountain reflections, seals and wildlife', 'Reflections are perfect in still conditions. Include mountains for scale. Sunrise/sunset creates magic.', 8),
('9', 'Falls of Glomach', 'Highland', 'Hidden Waterfall', 57.2567, -5.3456, 'One of Britain''s highest waterfalls at 370 feet. A spectacular single-drop fall hidden in a remote Highland glen.', 'Long hike from Dorusduain in Glen Elchaig. 6-mile round trip through rough terrain. Not for casual walkers.', '{"May", "June", "July", "August", "September"}', 'Expert', true, 'Dornie', 'Britain''s highest single-drop waterfall, completely remote setting', 'Use slow shutter for silk effect. Include surrounding cliff for scale. Very slippery rocks - be careful.', 9),
('10', 'Keiss Castle Beach', 'Highland', 'Coastal Feature', 58.6789, -3.1067, 'Ruined clifftop castle overlooking a hidden pebble beach with spectacular sea stacks and rock formations.', 'Drive to Keiss village and park near the old castle. Short walk along clifftop path. Beach access via steep path.', '{"April", "May", "June", "July", "August", "September"}', 'Moderate', true, 'Wick', 'Ruined castle, colorful sea stacks, secluded pebble beach', 'Dramatic skies enhance the moody atmosphere. Include castle ruins. Watch tides for beach access.', 10),
('11', 'Bone Caves', 'Highland', 'Cave System', 58.1456, -4.8567, 'Ancient limestone caves where Paleolithic remains were discovered. Hidden high on a mountainside with stunning views.', 'Park at Inchnadamph and hike 2 miles up steep hill path. The caves are at 800ft elevation. Torch essential.', '{"April", "May", "June", "July", "August", "September"}', 'Challenging', true, 'Inchnadamph', 'Paleolithic archaeological site, mountain views, ancient limestone formations', 'Headlamp for cave photography. Wide shots capture the elevated location. Include valley views.', 11),
('12', 'Secret Beach of Morar', 'Highland', 'Secret Beach', 56.9678, -5.8345, 'White sand beach with turquoise water rivaling the Caribbean. Often deserted despite its stunning beauty.', 'Drive through Morar village and follow signs to Silver Sands. Park and walk north along the coast for 15 minutes.', '{"May", "June", "July", "August", "September"}', 'Easy', false, 'Morar', 'White sand, turquoise water, views to Small Isles', 'Emphasize the tropical colors. Include islands in background. Best in bright sunlight.', 12),
('13', 'Duncansby Head Stacks', 'Highland', 'Coastal Feature', 58.6445, -3.0234, 'Dramatic sea stacks and natural arches at Scotland''s most northeasterly point. More spectacular than John O''Groats nearby.', 'Drive to Duncansby Head lighthouse from John O''Groats. Short walk from car park to viewpoints along the clifftop.', '{"April", "May", "June", "July", "August", "September"}', 'Easy', false, 'John O''Groats', 'Towering sea stacks, natural arches, puffin colonies', 'Classic lighthouse shots. Include stacks for drama. Puffins nest May-August. Mind the cliff edges.', 13),
('14', 'Devil''s Pulpit', 'Stirling', 'Hidden Waterfall', 56.0789, -4.3567, 'Narrow gorge with blood-red water created by red sandstone. A mystical and otherworldly hidden gem near Glasgow.', 'Park at Finnich Glen car park near Killearn. Short but steep hike down into the gorge. Can be slippery when wet.', '{"April", "May", "June", "July", "August", "September"}', 'Moderate', true, 'Killearn', 'Red sandstone gorge, blood-red water, mystical atmosphere', 'The red water is the star. Contrast with green moss. Use tripod for sharp shots in low light.', 14),
('15', 'St. Kilda', 'Outer Hebrides', 'Remote Island', 57.8123, -8.5789, 'Britain''s most remote inhabited island until 1930. Now a UNESCO World Heritage site with incredible wildlife and ruins.', 'Only accessible by organized boat trips from Harris or Lewis. Weather dependent. Full day or multi-day trips available.', '{"May", "June", "July", "August", "September"}', 'Expert', false, 'Leverburgh', 'Abandoned village, massive seabird colonies, dramatic cliffs', 'Capture the isolation and abandonment. Massive puffin colonies. Weather changes rapidly.', 15),
('16', 'Loch Katrine', 'Stirling', 'Natural Wonder', 56.2456, -4.5789, 'Pristine loch in the heart of the Trossachs, inspiration for Sir Walter Scott''s "Lady of the Lake".', 'Drive to Trossachs Pier car park. Steamship trips available or walk/cycle around the loch on traffic-free roads.', '{"April", "May", "June", "July", "August", "September", "October"}', 'Easy', false, 'Aberfoyle', 'Historic steamship, traffic-free roads, perfect reflections', 'Early morning for glass-like reflections. Include historic steamship. Autumn colors are spectacular.', 16),
('17', 'Corrieshalloch Gorge', 'Highland', 'Natural Wonder', 57.7456, -4.9567, 'Spectacular gorge with 150ft waterfall viewed from a Victorian suspension bridge and viewing platform.', 'Park at A835 Braemore junction. Short walk to suspension bridge and viewing platforms. Wheelchair accessible.', '{"April", "May", "June", "July", "August", "September"}', 'Easy', false, 'Ullapool', 'Victorian suspension bridge, dramatic gorge, powerful waterfall', 'Include the suspension bridge in shots. Use slow shutter for waterfall. Autumn foliage adds color.', 17),
('18', 'Bow Fiddle Rock', 'Moray', 'Coastal Feature', 57.6789, -2.9456, 'Natural rock arch resembling a bow fiddle. One of Scotland''s most photographed coastal features.', 'Drive to Portknockie village and park near the harbor. Short cliff walk to viewing area above the rock formation.', '{"April", "May", "June", "July", "August", "September"}', 'Easy', false, 'Portknockie', 'Perfect natural arch, dramatic clifftop views, fishing village', 'Classic arch shot from clifftop. Include village for context. Sunset shots are spectacular.', 18),
('19', 'Plodda Falls', 'Highland', 'Hidden Waterfall', 57.2678, -4.6789, 'Impressive 46-meter waterfall in ancient Caledonian forest with Victorian viewing platform high above.', 'Drive from Cannich and follow forest track signs to car park. Well-maintained paths and viewing platforms.', '{"April", "May", "June", "July", "August", "September"}', 'Easy', false, 'Cannich', 'Tall single-drop waterfall, ancient forest, Victorian engineering', 'Include the viewing platform. Forest context adds to composition. Use neutral density filter.', 19),
('20', 'Ballantrae Beach', 'South Ayrshire', 'Secret Beach', 55.1089, -4.9678, 'Long sandy beach backed by dunes with views to Ailsa Craig. Often empty despite easy access.', 'Drive to Ballantrae village and follow signs to beach car park. Easy walk across dunes to beach.', '{"April", "May", "June", "July", "August", "September", "October"}', 'Easy', false, 'Ballantrae', 'Long sandy beach, views to Ailsa Craig, empty beaches', 'Include Ailsa Craig in background shots. Beautiful at any time of day. Great for long exposures.', 20),
('21', 'Green Loch', 'Highland', 'Natural Wonder', 57.5678, -4.2345, 'Mysterious green-colored loch hidden in the Cairngorms with unknown depth and strange legends.', 'Hike from Glen More visitor centre. 3-mile walk through Caledonian pine forest. Well-marked trail.', '{"May", "June", "July", "August", "September"}', 'Moderate', true, 'Aviemore', 'Mysterious green water, ancient pine forest, complete silence', 'Emphasize the unusual green color. Include ancient pines for scale. Very still water reflects perfectly.', 21),
('22', 'Tolsta Beach', 'Outer Hebrides', 'Secret Beach', 58.3456, -6.1789, 'Remote beach on Lewis with huge waves, sea stacks, and complete isolation. Feels like the edge of the world.', 'Drive to end of road at Tolsta. Park and walk 30 minutes along clifftop path to reach the most spectacular section.', '{"April", "May", "June", "July", "August", "September"}', 'Moderate', true, 'Stornoway', 'Huge Atlantic waves, sea stacks, complete isolation', 'Dramatic wave action. Include sea stacks. Very windy - secure equipment. Atlantic storms create drama.', 22),
('23', 'Kelpies'' Pool', 'Scottish Borders', 'Hidden Waterfall', 55.5234, -2.7890, 'Hidden waterfall and deep pool in the Yarrow Valley, associated with Scottish folklore about water spirits.', 'Park in Yarrow village and follow the old drove road. 2-mile walk through moorland to hidden valley.', '{"April", "May", "June", "July", "August", "September"}', 'Moderate', true, 'Selkirk', 'Deep dark pool, hidden waterfall, folklore connections', 'Dark moody water creates atmosphere. Include surrounding moorland. Best after rain for full flow.', 23),
('24', 'Singing Sands', 'Highland', 'Secret Beach', 56.7890, -6.0123, 'Beach that literally sings when you walk on it due to unique sand composition. Magical acoustic phenomenon.', 'Take CalMac ferry to Eigg, then walk 40 minutes from pier along coastal path. Only accessible at low tide.', '{"May", "June", "July", "August", "September"}', 'Moderate', true, 'Eigg Ferry', 'Musical sand, unique geological phenomenon, Small Isles views', 'Capture people walking to show the singing effect. Include Small Isles backdrop. Time visit with tides.', 24),
('25', 'Knockan Crag', 'Highland', 'Natural Wonder', 58.0123, -5.2456, 'Geological wonder where ancient rocks sit on top of younger ones, defying normal geology.', 'Located on A835 north of Ullapool. Boardwalk trail and viewing platform make it accessible for all.', '{"April", "May", "June", "July", "August", "September"}', 'Easy', false, 'Ullapool', 'Unique geology, educational trail, panoramic Highland views', 'Include the geological formations. Wide views show the landscape context. Educational aspect adds interest.', 25),
('26', 'Carsaig Arches', 'Isle of Mull', 'Coastal Feature', 56.2789, -5.9012, 'Spectacular natural arches carved by the sea, accessible only at low tide via a challenging coastal walk.', 'Drive to Carsaig and park at road end. 5-mile round trip along rough coastal path. Check tide times carefully.', '{"April", "May", "June", "July", "August", "September"}', 'Challenging', true, 'Bunessan', 'Natural arches, dramatic coastline, tide-dependent access', 'Time visit with low tide. Include scale with people. Rough seas create dramatic spray shots.', 26),
('27', 'Mealt Falls', 'Isle of Skye', 'Hidden Waterfall', 57.6234, -6.1890, 'Waterfall that drops directly into the sea from high cliffs, creating a dramatic coastal spectacle.', 'Located on A855 near Kilt Rock. Roadside parking and short walk to viewpoint. Also accessible from above.', '{"April", "May", "June", "July", "August", "September"}', 'Easy', false, 'Staffin', 'Waterfall into sea, dramatic cliffs, roadside accessibility', 'Include the cliff context. Use telephoto to compress the scene. Rainbow often appears in spray.', 27),
('28', 'Rackwick Bay', 'Orkney', 'Secret Beach', 58.9567, -3.3456, 'Remote sandy bay on Hoy surrounded by towering cliffs and the famous Old Man of Hoy sea stack.', 'Take ferry to Hoy then drive to road end at Rackwick. Short walk to beach and longer hike to Old Man of Hoy.', '{"May", "June", "July", "August", "September"}', 'Moderate', true, 'Stromness', 'Red sandstone cliffs, Old Man of Hoy, complete isolation', 'Include Old Man of Hoy in wider shots. Red sandstone colors are unique. Very windy location.', 28),
('29', 'Linn of Dee', 'Aberdeenshire', 'Natural Wonder', 57.0456, -3.4789, 'Narrow rocky gorge where the River Dee is forced through a tight gap, creating swirling pools and cascades.', 'Drive to Linn of Dee car park west of Braemar. Short walk from car park to various viewpoints along the gorge.', '{"April", "May", "June", "July", "August", "September"}', 'Easy', false, 'Braemar', 'Narrow gorge, swirling pools, ancient Scots pines', 'Include the narrow gorge walls. Slow shutter shows water movement. Include ancient pines for context.', 29),
('30', 'Chanonry Point', 'Highland', 'Coastal Feature', 57.5789, -4.0890, 'Famous for the best dolphin watching in Europe from the beach. Bottle-nose dolphins hunt in the tide race.', 'Drive to Chanonry Point near Fortrose. Park and walk to the lighthouse point. Best 2 hours before high tide.', '{"April", "May", "June", "July", "August", "September", "October"}', 'Easy', false, 'Fortrose', 'Dolphin watching, lighthouse, tide race phenomenon', 'Long telephoto essential for dolphins. Include lighthouse for context. Time visit with tides.', 30)
ON CONFLICT (id) DO NOTHING;

-- Success message
SELECT '30 Scottish hidden gems data synchronized successfully!' as status;
