-- Insert 20 spectacular Scottish lochs
INSERT INTO lochs (id, name, region, type, length_km, max_depth_m, latitude, longitude, description, activities, best_seasons, famous_for, nearest_town, rank) VALUES
('1', 'Loch Ness', 'Highland', 'Freshwater Loch', 36.3, 230, 57.3229, -4.4244, 'Scotland''s most famous loch, home of the legendary Loch Ness Monster. The largest loch by volume in the British Isles, stretching 36km through the Great Glen.', '{"Monster spotting", "Boat trips", "Castle visits", "Hiking", "Photography"}', '{"April", "May", "June", "July", "August", "September", "October"}', 'The Loch Ness Monster (Nessie) and its mysterious depths', 'Inverness', 1),
('2', 'Loch Lomond', 'Central Scotland', 'Freshwater Loch', 36.4, 190, 56.1089, -4.6206, 'Scotland''s largest loch by surface area and part of the first National Park. Beautiful islands and surrounded by mountains, offering endless recreational opportunities.', '{"Boating", "Swimming", "Hiking", "Island hopping", "Cycling", "Fishing"}', '{"April", "May", "June", "July", "August", "September", "October"}', 'Being Scotland''s largest loch and the song "The Bonnie Banks"', 'Balloch', 2),
('3', 'Loch Katrine', 'Stirling', 'Freshwater Loch', 12.5, 151, 56.2567, -4.5789, 'The heart of the Trossachs, inspiration for Sir Walter Scott''s "Lady of the Lake". Pure mountain water that supplies Glasgow, surrounded by beautiful Highland scenery.', '{"Steamship cruises", "Cycling", "Hiking", "Photography", "Wildlife watching"}', '{"April", "May", "June", "July", "August", "September", "October"}', 'Sir Walter Scott''s "Lady of the Lake" and Victorian steamship cruises', 'Callander', 3),
('4', 'Loch Earn', 'Stirling', 'Freshwater Loch', 10.5, 87, 56.3856, -4.2067, 'Beautiful loch in the heart of Scotland surrounded by mountains. Popular for water sports and home to the famous Lochearnhead Water Sports Centre.', '{"Water skiing", "Jet skiing", "Sailing", "Fishing", "Mountain biking", "Hiking"}', '{"May", "June", "July", "August", "September"}', 'Water sports and the annual Loch Earn Highland Games', 'Lochearnhead', 4),
('5', 'Loch Awe', 'Argyll and Bute', 'Freshwater Loch', 41.0, 94, 56.4089, -5.0267, 'Scotland''s longest freshwater loch, stretching 41km through stunning Highland scenery. Home to the romantic ruins of Kilchurn Castle.', '{"Boat trips", "Fishing", "Castle visits", "Hiking", "Photography", "Kayaking"}', '{"April", "May", "June", "July", "August", "September", "October"}', 'Being Scotland''s longest freshwater loch and Kilchurn Castle', 'Oban', 5),
('6', 'Loch Tay', 'Highland', 'Freshwater Loch', 23.2, 150, 56.5167, -4.1133, 'Beautiful Highland loch overlooked by Ben Lawers, Scotland''s 10th highest mountain. Rich in wildlife and archaeological sites including ancient crannogs.', '{"Crannog visits", "Ben Lawers hiking", "Fishing", "Cycling", "Wildlife watching", "Watersports"}', '{"April", "May", "June", "July", "August", "September", "October"}', 'Ancient crannogs (lake dwellings) and Ben Lawers National Nature Reserve', 'Aberfeldy', 6),
('7', 'Loch Tummel', 'Highland', 'Freshwater Loch', 11.0, 43, 56.7067, -3.9133, 'Scenic loch in Highland Perthshire, famous for the Queen''s View - one of Scotland''s most photographed viewpoints. Part of beautiful Tummel Valley.', '{"Photography", "Hiking", "Cycling", "Fishing", "Forest walks", "Dam visits"}', '{"April", "May", "June", "July", "August", "September", "October"}', 'The Queen''s View viewpoint and hydroelectric power generation', 'Pitlochry', 7),
('8', 'Loch Achray', 'Stirling', 'Freshwater Loch', 2.5, 25, 56.2333, -4.4667, 'Small but perfectly formed loch in the heart of the Trossachs. Peaceful setting surrounded by woodland and mountains, perfect for quiet contemplation.', '{"Fishing", "Walking", "Photography", "Picnicking", "Wildlife watching", "Quiet reflection"}', '{"April", "May", "June", "July", "August", "September", "October"}', 'Tranquil beauty and its role in the Trossachs water cycle', 'Aberfoyle', 8),
('9', 'Loch Vennachar', 'Stirling', 'Freshwater Loch', 6.0, 38, 56.2167, -4.3833, 'Beautiful loch in the Trossachs, popular with anglers and nature lovers. Part of Glasgow''s water supply system with excellent walking opportunities around its shores.', '{"Fishing", "Walking", "Cycling", "Photography", "Birdwatching", "Canoeing"}', '{"April", "May", "June", "July", "August", "September", "October"}', 'Excellent brown trout fishing and peaceful woodland walks', 'Callander', 9),
('10', 'Loch Rannoch', 'Highland', 'Freshwater Loch', 15.7, 134, 56.6833, -4.2667, 'Remote and wild loch in Highland Perthshire, gateway to the Rannoch Moor. Stunning mountain scenery and one of Scotland''s most isolated and beautiful lochs.', '{"Hiking", "Photography", "Wildlife watching", "Fishing", "Camping", "Stargazing"}', '{"May", "June", "July", "August", "September"}', 'Gateway to Rannoch Moor and remote Highland wilderness', 'Kinloch Rannoch', 10),
('11', 'Loch Maree', 'Highland', 'Freshwater Loch', 20.0, 114, 57.7167, -5.4833, 'Magnificent loch in Wester Ross surrounded by ancient Caledonian pine forest. Multiple islands and spectacular mountain backdrop including Slioch.', '{"Hiking", "Photography", "Wildlife watching", "Fishing", "Island exploring", "Nature study"}', '{"May", "June", "July", "August", "September", "October"}', 'Ancient Caledonian pine forest and Isle Maree with ancient burial ground', 'Kinlochewe', 11),
('12', 'Loch Torridon', 'Highland', 'Sea Loch', 15.0, 87, 57.5500, -5.6833, 'Dramatic sea loch surrounded by some of Scotland''s most spectacular mountains. Crystal clear waters reflecting towering peaks.', '{"Sea kayaking", "Mountain climbing", "Photography", "Wildlife watching", "Boat trips", "Diving"}', '{"May", "June", "July", "August", "September", "October"}', 'Spectacular Torridon mountains and pristine Highland scenery', 'Torridon', 12),
('13', 'Loch Shiel', 'Highland', 'Freshwater Loch', 28.0, 128, 56.8000, -5.4000, 'Long, narrow loch stretching from Glenfinnan to Acharacle. Famous for its role in Bonnie Prince Charlie''s campaign and Harry Potter films.', '{"Boat trips", "Hiking", "Photography", "Jacobite history", "Film location tours", "Fishing"}', '{"April", "May", "June", "July", "August", "September", "October"}', 'Glenfinnan Monument, Jacobite history, and Harry Potter filming location', 'Glenfinnan', 13),
('14', 'Loch Duich', 'Highland', 'Sea Loch', 8.0, 65, 57.2667, -5.5167, 'Beautiful sea loch dominated by the Five Sisters of Kintail mountains. Home to the iconic Eilean Donan Castle.', '{"Castle visits", "Photography", "Hiking", "Kayaking", "Wildlife watching", "Mountain climbing"}', '{"April", "May", "June", "July", "August", "September", "October"}', 'Eilean Donan Castle and the Five Sisters of Kintail mountains', 'Kyle of Lochalsh', 14),
('15', 'Loch Assynt', 'Highland', 'Freshwater Loch', 6.0, 85, 58.2000, -4.9167, 'Remote Highland loch surrounded by distinctive Assynt mountains including Suilven and Canisp. Ancient landscape of Lewisian gneiss.', '{"Hiking", "Photography", "Geology study", "Wildlife watching", "Fishing", "Wild camping"}', '{"May", "June", "July", "August", "September"}', 'Distinctive mountain peaks and ancient geological landscape', 'Lochinver', 15),
('16', 'Loch Fyne', 'Argyll and Bute', 'Sea Loch', 65.0, 184, 56.1667, -5.1833, 'Scotland''s longest sea loch, famous for its seafood, particularly oysters and kippers. Beautiful coastal scenery and charming fishing villages.', '{"Seafood dining", "Boat trips", "Fishing", "Coastal walks", "Photography", "Cycling"}', '{"April", "May", "June", "July", "August", "September", "October"}', 'World-famous seafood, particularly Loch Fyne oysters and kippers', 'Inveraray', 16),
('17', 'Loch Etive', 'Argyll and Bute', 'Sea Loch', 30.0, 150, 56.4833, -5.1833, 'Dramatic sea loch stretching inland from Oban. Surrounded by mountains and featuring tidal rapids at the Falls of Lora.', '{"Kayaking", "Photography", "Hiking", "Tidal bore watching", "Mountain climbing", "Wildlife watching"}', '{"April", "May", "June", "July", "August", "September", "October"}', 'Tidal rapids at Falls of Lora and dramatic mountain scenery', 'Oban', 17),
('18', 'Loch Long', 'Argyll and Bute', 'Sea Loch', 23.0, 75, 56.1000, -4.8500, 'Scenic sea loch stretching north from the Firth of Clyde. Popular for water sports and surrounded by beautiful hills.', '{"Sailing", "Water skiing", "Kayaking", "Hiking", "Photography", "Diving"}', '{"April", "May", "June", "July", "August", "September", "October"}', 'Water sports and beautiful Highland scenery close to Glasgow', 'Arrochar', 18),
('19', 'Loch Coruisk', 'Highland', 'Freshwater Loch', 2.5, 38, 57.2167, -6.1833, 'Remote and dramatic loch in the heart of the Cuillin mountains on Skye. Accessible only by boat or challenging hike.', '{"Boat trips", "Extreme hiking", "Photography", "Rock climbing", "Wild swimming", "Wilderness experience"}', '{"May", "June", "July", "August", "September"}', 'Remote location and dramatic Cuillin mountain setting on Skye', 'Elgol', 19),
('20', 'Loch Linnhe', 'Highland', 'Sea Loch', 50.0, 154, 56.7167, -5.1167, 'Major sea loch extending from Fort William to the Firth of Lorn. Important transportation route with ferry connections.', '{"Ferry travel", "Coastal walks", "Photography", "Wildlife watching", "Kayaking", "Fishing"}', '{"April", "May", "June", "July", "August", "September", "October"}', 'Transportation hub and gateway to the Western Highlands and Islands', 'Fort William', 20);

-- Success message for lochs
SELECT 'All 20 lochs inserted successfully!' as status;
